"""files_page_cache

Revision ID: 1a5662d00874
Revises: bad98e8dd5aa
Create Date: 2026-05-08 01:53:45.516870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a5662d00874'
down_revision: Union[str, Sequence[str], None] = 'bad98e8dd5aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files_page_cache',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('params_hash', sa.String(length=32), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'params_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files_page_cache')
    # ### end Alembic commands ###
