"""exam main_type

Revision ID: 29bfe4193df0
Revises: 800af1e9e52c
Create Date: 2026-05-07 00:35:18.377571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29bfe4193df0'
down_revision: Union[str, Sequence[str], None] = '800af1e9e52c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('main_type', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'main_type')
    # ### end Alembic commands ###
