"""lessons and schedule_sync_state

Revision ID: 6d80c9e6f97d
Revises: c322976fbbc7
Create Date: 2026-05-06 15:38:59.610145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d80c9e6f97d'
down_revision: Union[str, Sequence[str], None] = 'c322976fbbc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('edu_year_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.SmallInteger(), nullable=False),
    sa.Column('start', sa.Time(), nullable=False),
    sa.Column('end', sa.Time(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('subject_code', sa.String(length=128), nullable=True),
    sa.Column('lesson_type', sa.String(length=64), nullable=True),
    sa.Column('room', sa.String(length=32), nullable=True),
    sa.Column('building', sa.String(length=32), nullable=True),
    sa.Column('teacher', sa.String(length=255), nullable=True),
    sa.Column('week_parity', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lessons_user_year_day', 'lessons', ['user_id', 'edu_year_id', 'day'], unique=False)
    op.create_table('schedule_sync_state',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('edu_year_id', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'edu_year_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_sync_state')
    op.drop_index('ix_lessons_user_year_day', table_name='lessons')
    op.drop_table('lessons')
    # ### end Alembic commands ###
