"""exams and exam_sync_state

Revision ID: 800af1e9e52c
Revises: 91b95269842f
Create Date: 2026-05-07 00:22:39.699678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '800af1e9e52c'
down_revision: Union[str, Sequence[str], None] = '91b95269842f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_sync_state',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('edu_year_id', sa.Integer(), nullable=False),
    sa.Column('edu_semester_id', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'edu_year_id', 'edu_semester_id')
    )
    op.create_table('exams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('edu_year_id', sa.Integer(), nullable=False),
    sa.Column('edu_semester_id', sa.Integer(), nullable=False),
    sa.Column('exam_type_id', sa.Integer(), nullable=True),
    sa.Column('exam_type_name', sa.String(length=64), nullable=False),
    sa.Column('unec_exam_id', sa.Integer(), nullable=True),
    sa.Column('subject_code', sa.String(length=128), nullable=True),
    sa.Column('subject_name', sa.Text(), nullable=False),
    sa.Column('subject_full', sa.Text(), nullable=True),
    sa.Column('form', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('entry_score', sa.SmallInteger(), nullable=True),
    sa.Column('exam_score', sa.SmallInteger(), nullable=True),
    sa.Column('final_score', sa.SmallInteger(), nullable=True),
    sa.Column('grade_letter', sa.String(length=4), nullable=True),
    sa.Column('grade_label', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exams_user_date', 'exams', ['user_id', 'date'], unique=False)
    op.create_index('ix_exams_user_year_sem', 'exams', ['user_id', 'edu_year_id', 'edu_semester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exams_user_year_sem', table_name='exams')
    op.drop_index('ix_exams_user_date', table_name='exams')
    op.drop_table('exams')
    op.drop_table('exam_sync_state')
    # ### end Alembic commands ###
