"""subjects marks grading details and grades sync state

Revision ID: 91b95269842f
Revises: 6d80c9e6f97d
Create Date: 2026-05-06 15:46:23.975259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91b95269842f'
down_revision: Union[str, Sequence[str], None] = '6d80c9e6f97d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades_sync_state',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('edu_year_id', sa.Integer(), nullable=False),
    sa.Column('edu_semester_id', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'edu_year_id', 'edu_semester_id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('edu_year_id', sa.Integer(), nullable=False),
    sa.Column('edu_semester_id', sa.Integer(), nullable=False),
    sa.Column('unec_subject_id', sa.Integer(), nullable=False),
    sa.Column('edu_form_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('group_name', sa.Text(), nullable=True),
    sa.Column('credits', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'edu_year_id', 'edu_semester_id', 'unec_subject_id', name='uq_subjects_user_year_sem_unec_id')
    )
    op.create_index('ix_subjects_user_year_sem', 'subjects', ['user_id', 'edu_year_id', 'edu_semester_id'], unique=False)
    op.create_table('marks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('lesson_type_id', sa.Integer(), nullable=False),
    sa.Column('lesson_type_name', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('mark_code', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'lesson_type_id', 'date', 'topic', name='uq_marks_subject_type_date_topic')
    )
    op.create_index('ix_marks_subject_type', 'marks', ['subject_id', 'lesson_type_id'], unique=False)
    op.create_table('subject_grading_details',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('lesson_type_id', sa.Integer(), nullable=False),
    sa.Column('final_eval', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheme', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('course_work', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('independent_work', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('writing', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id', 'lesson_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject_grading_details')
    op.drop_index('ix_marks_subject_type', table_name='marks')
    op.drop_table('marks')
    op.drop_index('ix_subjects_user_year_sem', table_name='subjects')
    op.drop_table('subjects')
    op.drop_table('grades_sync_state')
    # ### end Alembic commands ###
