"""marks: drop unique constraint

Revision ID: bad98e8dd5aa
Revises: 364668a757c7
Create Date: 2026-05-08 01:19:05.006234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad98e8dd5aa'
down_revision: Union[str, Sequence[str], None] = '364668a757c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_marks_subject_type_date_topic'), 'marks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_marks_subject_type_date_topic'), 'marks', ['subject_id', 'lesson_type_id', 'date', 'topic'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
